### ISSUE TITLE
can not find resource

### ISSUE THREAD

**Issue by Kyson** [k0shk0sh/KAM#1]
there are some strings undefined in string.xml

at homeactivity.java

productsList.addAll(Arrays.asList(getResources().getStringArray(R.array.in_app_billing)));
mHelper = new IabHelper(this, getString(R.string.base64));

error:cannot find in_app_billing  and base64

**Comment by k0shk0sh** [comment]
these are private resources i can't share them :).

**Comment by k0shk0sh** [comment]
you can pull again, i have add the resources.

**Comment by Kyson** [comment]
thx a lot :+1:
