### ISSUE TITLE
Build error 

### ISSUE THREAD

**Issue by ghost** [k0shk0sh/KAM#2]
when i get code and build project ,i get some error as below:
 productsList.addAll(Arrays.asList(getResources().getStringArray(R.array.in_app_billing)));
 mHelper = new IabHelper(this, getString(R.string.base64));

Error:(134, 80) error: cannot find symbol variable in_app_billing
Error:(135, 57) error: cannot find symbol variable base64

:)

**Comment by k0shk0sh** [comment]
these are private resources, i can't share them, thanks for understanding, however to fix the issue, you could create them in strings file.

**Comment by k0shk0sh** [comment]
you can pull again, i have add the resources.

**Comment by ghost** [comment]
Thank you. I understand :)
